### ISSUE TITLE
Error while running eval.py

### ISSUE THREAD

**Issue by MLbyML** [Thinklab-SJTU/PCA-GM#5]
Hello,

I have cudatoolkit  9.0 and pytorch 1.1.0 setup in my environment. 
Running `python train_eval.py --cfg experiments/vgg16_gmn_voc.yaml` produces the following error for me. Would you have any suggestions on how I could fix this? Thank you for your time!

```
Traceback (most recent call last):
  File "/home/manan/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 949, in _build_extension_module
    check=True)
  File "/home/manan/Softwares/anaconda3/envs/pcagmEnv/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_eval.py", line 8, in <module>
    from data.data_loader import GMDataset, get_dataloader
  File "/home/manan/Desktop/jug-pc-x/05_Repositories/PCA-GM/data/data_loader.py", line 10, in <module>
    from utils.fgm import kronecker_sparse
  File "/home/manan/Desktop/jug-pc-x/05_Repositories/PCA-GM/utils/fgm.py", line 4, in <module>
    from utils.sparse import bilinear_diag_torch
  File "/home/manan/Desktop/jug-pc-x/05_Repositories/PCA-GM/utils/sparse.py", line 7, in <module>
    from sparse_torch import CSRMatrix3d, CSCMatrix3d
  File "/home/manan/Desktop/jug-pc-x/05_Repositories/PCA-GM/sparse_torch/__init__.py", line 5, in <module>
    from .csx_matrix import CSRMatrix3d, CSCMatrix3d, dot, concatenate
  File "/home/manan/Desktop/jug-pc-x/05_Repositories/PCA-GM/sparse_torch/csx_matrix.py", line 13, in <module>
    '/usr/include/python{}.{}/'.format(sys.version_info.major, sys.version_info.minor)]
  File "/home/manan/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 644, in load
    is_python_module)
  File "/home/manan/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 813, in _jit_compile
    with_cuda=with_cuda)
  File "/home/manan/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 866, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/manan/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 962, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'sparse_dot': b"[1/3] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=sparse_dot -DTORCH_API_INCLUDE_EXTENSION_H -I/usr/include/python3.7 -isystem /home/manan/.local/lib/python3.7/site-packages/torch/include -isystem /home/manan/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/manan/.local/lib/python3.7/site-packages/torch/include/TH -isystem /home/manan/.local/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/manan/Softwares/anaconda3/envs/pcagmEnv/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /home/manan/Desktop/jug-pc-x/05_Repositories/PCA-GM/extension/sparse_dot/csr_dot_csc_cuda.cu -o csr_dot_csc_cuda.cuda.o\nFAILED: csr_dot_csc_cuda.cuda.o \n/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=sparse_dot -DTORCH_API_INCLUDE_EXTENSION_H -I/usr/include/python3.7 -isystem /home/manan/.local/lib/python3.7/site-packages/torch/include -isystem /home/manan/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/manan/.local/lib/python3.7/site-packages/torch/include/TH -isystem /home/manan/.local/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/manan/Softwares/anaconda3/envs/pcagmEnv/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /home/manan/Desktop/jug-pc-x/05_Repositories/PCA-GM/extension/sparse_dot/csr_dot_csc_cuda.cu -o csr_dot_csc_cuda.cuda.o\nIn file included from /usr/local/cuda/include/host_config.h:50:0,\n                 from /usr/local/cuda/include/cuda_runtime.h:78,\n                 from <command-line>:0:\n/usr/local/cuda/include/crt/host_config.h:121:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!\n #error -- unsupported GNU version! gcc versions later than 6 are not supported!\n  ^~~~~\n[2/3] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=sparse_dot -DTORCH_API_INCLUDE_EXTENSION_H -I/usr/include/python3.7 -isystem /home/manan/.local/lib/python3.7/site-packages/torch/include -isystem /home/manan/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/manan/.local/lib/python3.7/site-packages/torch/include/TH -isystem /home/manan/.local/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/manan/Softwares/anaconda3/envs/pcagmEnv/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /home/manan/Desktop/jug-pc-x/05_Repositories/PCA-GM/extension/sparse_dot/csr_dot_diag_cuda.cu -o csr_dot_diag_cuda.cuda.o\nFAILED: csr_dot_diag_cuda.cuda.o \n/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=sparse_dot -DTORCH_API_INCLUDE_EXTENSION_H -I/usr/include/python3.7 -isystem /home/manan/.local/lib/python3.7/site-packages/torch/include -isystem /home/manan/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/manan/.local/lib/python3.7/site-packages/torch/include/TH -isystem /home/manan/.local/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/manan/Softwares/anaconda3/envs/pcagmEnv/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /home/manan/Desktop/jug-pc-x/05_Repositories/PCA-GM/extension/sparse_dot/csr_dot_diag_cuda.cu -o csr_dot_diag_cuda.cuda.o\nIn file included from /usr/local/cuda/include/host_config.h:50:0,\n                 from /usr/local/cuda/include/cuda_runtime.h:78,\n                 from <command-line>:0:\n/usr/local/cuda/include/crt/host_config.h:121:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!\n #error -- unsupported GNU version! gcc versions later than 6 are not supported!\n  ^~~~~\nninja: build stopped: subcommand failed.\n"
```

**Comment by rogerwwww** [comment]
Hi, as suggested in the output: 
```
#error -- unsupported GNU version! gcc versions later than 6 are not supported!
```

Please chose a suitable version of gcc (also >4.8) to compile this project!

**Comment by MLbyML** [comment]
Okay, thanks for the tip. I downgraded it to gcc version 5.4 and am running this on TitanX. This leads to an unsupported gpu architecture 'compute_61' error.  Any suggestions on how this could be fixed? 
```
RuntimeError: Error building extension 'sparse_dot': [1/4] /usr/bin/nvcc -DTORCH_EXTENSION_NAME=sparse_dot -DTORCH_API_INCLUDE_EXTENSION_H -I/usr/include/python3.7 -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include/TH -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include/THC -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++11 -c /home/lalit/Desktop/05_Repositories/PCA-GM/extension/sparse_dot/csr_dot_csc_cuda.cu -o csr_dot_csc_cuda.cuda.o
FAILED: csr_dot_csc_cuda.cuda.o 
/usr/bin/nvcc -DTORCH_EXTENSION_NAME=sparse_dot -DTORCH_API_INCLUDE_EXTENSION_H -I/usr/include/python3.7 -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include/TH -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include/THC -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++11 -c /home/lalit/Desktop/05_Repositories/PCA-GM/extension/sparse_dot/csr_dot_csc_cuda.cu -o csr_dot_csc_cuda.cuda.o
nvcc fatal   : Unsupported gpu architecture 'compute_61'
[2/4] /usr/bin/nvcc -DTORCH_EXTENSION_NAME=sparse_dot -DTORCH_API_INCLUDE_EXTENSION_H -I/usr/include/python3.7 -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include/TH -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include/THC -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++11 -c /home/lalit/Desktop/05_Repositories/PCA-GM/extension/sparse_dot/csr_dot_diag_cuda.cu -o csr_dot_diag_cuda.cuda.o
FAILED: csr_dot_diag_cuda.cuda.o 
/usr/bin/nvcc -DTORCH_EXTENSION_NAME=sparse_dot -DTORCH_API_INCLUDE_EXTENSION_H -I/usr/include/python3.7 -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include/TH -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include/THC -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++11 -c /home/lalit/Desktop/05_Repositories/PCA-GM/extension/sparse_dot/csr_dot_diag_cuda.cu -o csr_dot_diag_cuda.cuda.o
nvcc fatal   : Unsupported gpu architecture 'compute_61'
[3/4] c++ -MMD -MF sparse_dot.o.d -DTORCH_EXTENSION_NAME=sparse_dot -DTORCH_API_INCLUDE_EXTENSION_H -I/usr/include/python3.7 -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include/TH -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/lib/python3.7/site-packages/torch/include/THC -isystem /home/lalit/Desktop/02_SoftwareExecutables/anaconda3/envs/pcagmEnv/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/lalit/Desktop/05_Repositories/PCA-GM/extension/sparse_dot/sparse_dot.cpp -o sparse_dot.o
ninja: build stopped: subcommand failed.
```

**Comment by MLbyML** [comment]
Okay, it works now. Thanks for the tip!
