### ISSUE TITLE
Scipy.sparse got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by JiewenZhao** [Thinklab-SJTU/PCA-GM#8]
I got an error when training:
-------------------
Start training...
model on device: cuda:1
Epoch 0/19
lr = 1.00e-03
Traceback (most recent call last):
  File "/home/Raiser/Documents/zjw/MMM/PCA-GM/train_eval.py", line 228, in <module>
    start_epoch=cfg.TRAIN.START_EPOCH)
  File "/home/Raiser/Documents/zjw/MMM/PCA-GM/train_eval.py", line 72, in train_eval_model
    for inputs in dataloader['train']:
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/Raiser/Documents/zjw/MMM/PCA-GM/data/data_loader.py", line 136, in collate_fn
    K1G = CSRMatrix3d(K1G)
  File "/home/Raiser/Documents/zjw/MMM/PCA-GM/sparse_torch/csx_matrix.py", line 315, in __init__
    super(CSRMatrix3d, self).__init__(inp, shape, device)
  File "/home/Raiser/Documents/zjw/MMM/PCA-GM/sparse_torch/csx_matrix.py", line 84, in __init__
    self.indices, self.indptr, self.data, self.shape = from_ssp(inp, shape, device)
  File "/home/Raiser/Documents/zjw/MMM/PCA-GM/sparse_torch/csx_matrix.py", line 41, in from_ssp
    sp = inp_s[b].tocsr().astype(dtype=inp_s[b].dtype)
TypeError: astype() got an unexpected keyword argument 'dtype'

**Comment by rogerwwww** [comment]
Hi Jiewen,

It seems to be an issue of scipy. What's your version of scipy?

**Comment by JiewenZhao** [comment]
The version of scipy is 0.19.1

**Comment by rogerwwww** [comment]
It might be outdated. Could you try updating it to the latest version? By ``pip install -U scipy``

**Comment by JiewenZhao** [comment]
This problem has been solved. Thank you very much for your kind reply!
