### ISSUE TITLE
A debug error

### ISSUE THREAD

**Issue by JiewenZhao** [Thinklab-SJTU/PCA-GM#9]
Hi,
    I met a problem when I debug the code. But it has no error when running the code directly. Would you have any suggestions on how I could fix this? Thank you for your time!
Epoch 0/19
----------
lr = 1.00e-03
Traceback (most recent call last):
  File "/home/Raiser/Documents/zjw/MMM/PCA-GM/train_eval.py", line 231, in <module>
    start_epoch=cfg.TRAIN.START_EPOCH)
  File "/home/Raiser/Documents/zjw/MMM/PCA-GM/train_eval.py", line 72, in train_eval_model
    for inputs in dataloader['train']:
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 682, in __init__
    w.start()
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/multiprocessing/popen_fork.py", line 67, in _launch
    self.pid = os.fork()
  File "/home/Raiser/.pycharm_helpers/pydev/_pydev_bundle/pydev_monkey.py", line 598, in new_fork
    _on_forked_process()
  File "/home/Raiser/.pycharm_helpers/pydev/_pydev_bundle/pydev_monkey.py", line 73, in _on_forked_process
    pydevd.settrace_forked()
  File "/home/Raiser/.pycharm_helpers/pydev/pydevd.py", line 1867, in settrace_forked
    patch_multiprocessing=True,
  File "/home/Raiser/.pycharm_helpers/pydev/pydevd.py", line 1631, in settrace
    stop_at_frame,
  File "/home/Raiser/.pycharm_helpers/pydev/pydevd.py", line 1711, in _locked_settrace
    debugger.enable_tracing(apply_to_all_threads=True)
  File "/home/Raiser/.pycharm_helpers/pydev/pydevd.py", line 492, in enable_tracing
    pydevd_tracing.set_trace_to_threads(thread_trace_func)
  File "/home/Raiser/.pycharm_helpers/pydev/pydevd_tracing.py", line 241, in set_trace_to_threads
    result = lib.AttachDebuggerTracing(
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/Raiser/.pycharm_helpers/pydev/pydevd_attach_to_process/attach_linux_amd64.so: undefined symbol: AttachDebuggerTracing
Traceback (most recent call last):
  File "/home/Raiser/Documents/zjw/MMM/PCA-GM/train_eval.py", line 231, in <module>
    start_epoch=cfg.TRAIN.START_EPOCH)
  File "/home/Raiser/Documents/zjw/MMM/PCA-GM/train_eval.py", line 72, in train_eval_model
    for inputs in dataloader['train']:
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 682, in __init__
    w.start()
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/multiprocessing/popen_fork.py", line 67, in _launch
    self.pid = os.fork()
  File "/home/Raiser/.pycharm_helpers/pydev/_pydev_bundle/pydev_monkey.py", line 598, in new_fork
    _on_forked_process()
  File "/home/Raiser/.pycharm_helpers/pydev/_pydev_bundle/pydev_monkey.py", line 73, in _on_forked_process
    pydevd.settrace_forked()
  File "/home/Raiser/.pycharm_helpers/pydev/pydevd.py", line 1867, in settrace_forked
    patch_multiprocessing=True,
  File "/home/Raiser/.pycharm_helpers/pydev/pydevd.py", line 1631, in settrace
    stop_at_frame,
  File "/home/Raiser/.pycharm_helpers/pydev/pydevd.py", line 1711, in _locked_settrace
    debugger.enable_tracing(apply_to_all_threads=True)
  File "/home/Raiser/.pycharm_helpers/pydev/pydevd.py", line 492, in enable_tracing
    pydevd_tracing.set_trace_to_threads(thread_trace_func)
  File "/home/Raiser/.pycharm_helpers/pydev/pydevd_tracing.py", line 241, in set_trace_to_threads
    result = lib.AttachDebuggerTracing(
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/Raiser/.pycharm_helpers/pydev/pydevd_attach_to_process/attach_linux_amd64.so: undefined symbol: AttachDebuggerTracing
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/multiprocessing/util.py", line 319, in _exit_function
    p.join()
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/multiprocessing/process.py", line 119, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Traceback (most recent call last):
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 724, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if timeout < 0 or not self._poll(timeout):
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 10293) is killed by signal: Terminated. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Raiser/Documents/zjw/MMM/PCA-GM/train_eval.py", line 231, in <module>
    start_epoch=cfg.TRAIN.START_EPOCH)
  File "/home/Raiser/Documents/zjw/MMM/PCA-GM/train_eval.py", line 72, in train_eval_model
    for inputs in dataloader['train']:
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 771, in _get_data
    success, data = self._try_get_data()
  File "/home/Raiser/anaconda3/envs/pytorch1.1_py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 737, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 10293) exited unexpectedly

**Comment by JiewenZhao** [comment]
change DATALOADER_NUM to 0
